### ISSUE TITLE
The websocket is returning no results.

### ISSUE THREAD

**Issue by aaomidi** [CaliDog/certstream-js#1]
The javascript client is not printing out anything.

Stuck on:

```
Connection established to certstream! Waiting for messages...
```

**Comment by aaomidi** [comment]
I think the website was under load, its fixed now.

**Comment by Fitblip** [comment]
Hey @aaomidi - This is one of the problems with the CTLs in general actually, they don't tend to be a steady "stream" of certificates, so they tend to dump in batches (and it's just how the CTLs operate). 

I should add a blurb on developing with CertStream and better configurability to the libraries themselves, since developing against the `wss://certstream.calidog.io/develop` endpoint is much more preferred since it just dumps the 25 most recent certificates over and over until you disconnect.

**Comment by aaomidi** [comment]
I see, thank you for explaining what was going on!

**Comment by Fitblip** [comment]
Of course, thanks for your interest in the project! I'll be spending some time in coming weeks trying to figure out a good solution to this. 

Cheers!
